#:import dp kivy.metrics.dp
#:import sp kivy.metrics.sp

<Input1@TextInput>:
    size_hint_y: None
    height: dp(45)
    font_size: sp(18)
    multiline: False
    valign: "middle"
    halign: "left"
    padding: [dp(10), (self.height - self.line_height) / 2]

    background_normal: ""
    background_active: ""

    # 🔥 เปลี่ยนสีตอน focus
    canvas.before:
        Color:
            rgba: (1,1,1,1) if not self.focus else (0.9,0.9,0.9,1)
        Rectangle:
            pos: self.pos
            size: self.size

        Color:
            rgba: (0,0,0,1) if not self.focus else (0,0.5,1,1)
        Line:
            width: 1.0
            rectangle: (self.x, self.y, self.width, self.height)