<Connect1>:
    canvas.before:
        Color:
            rgba: 1,1,1,1
        Rectangle:
            pos: self.pos
            size: self.size
    BoxLayout:
        orientation:"vertical"
        padding:20
        spacing:15

        Label:
            text:"Available Riders"
            size_hint_y:None
            height:"50dp"
            font_size:"24sp"
            color:0,0,0,1

        Button:
            text:"SCAN"
            size_hint_y:None
            height:"55dp"
            font_size:"20sp"
            on_release:root.scan()

        Label:
            text:root.result_text
            size_hint_y:None
            height:"40dp"
            font_size:"18sp"
            color:0,0,0,1

        ScrollView:
            do_scroll_x:False

            GridLayout:
                id:rider_list
                cols:1
                spacing:10
                padding:10
                size_hint_y:None
                height:self.minimum_height

        AnchorLayout:
            anchor_x:"left"
            anchor_y:"bottom"

            Button:
                text:"Back"
                size_hint:None,None
                size:"80dp","40dp"
                on_press:root.go_to("home_customer")