<Home1>:
    canvas.before:
        Color:
            rgba: 1, 1, 1, 1
        Rectangle:
            pos: self.pos
            size: self.size

    BoxLayout:
        orientation: "vertical"
        padding: "40dp"
        spacing: "20dp"

        Label:
            text: "HOME(customer)"
            font_size: "32sp"
            color: 0, 0, 0, 1
            size_hint_y: None
            height: "50dp"

        Label:
            text: root.firstname + " " + root.lastname
            color: 0, 0, 0, 1
            font_size: "14sp"
            size_hint_y: None
            height: "20dp"

        Label:
            text: "Balance : " + root.money + " Baht"
            color: 0, 0, 0, 1
            font_size: "14sp"
            size_hint_y: None
            height: "30dp"

        Widget:

        Button1:
            text: "Request"
            on_press: root.go_to("request_ride")

        Button1:
            text: "Deposit"
            on_press: root.go_to("deposit")

        Widget:

        Button1:
            text: "Logout"
            on_press: root.logout()