<Home>:

    BoxLayout:
        orientation: "vertical"
        padding: "40dp"
        spacing: "20dp"

        Label:
            text: "HOME"
            font_size: "32sp"
            color: 0, 0, 0, 1

        Label:
            text: "Role : " + root.role
            color: 0, 0, 0, 1
            font_size: "14sp"
            size_hint_y: None
            height: "20dp"
            halign: "left"
            text_size: self.width, None

        Button1:
            text: "Logout"
            on_press: root.go_to("login")