<Register>:

    BoxLayout:
        orientation: "vertical"
        padding: "30dp"
        spacing: "10dp"

        Widget:
            size_hint_y: 0.05

        Label:
            text: "Register"
            font_size: "26sp"
            color: 0,0,0,1
            size_hint_y: None
            height: "50dp"

        Input1:
            hint_text: "First Name"
            id: firstname
            on_text: root.check_form()

        Input1:
            hint_text: "Last Name"
            id: lastname
            on_text: root.check_form()

        Input1:
            hint_text: "Email"
            id: email
            on_text: root.check_form()

        Input1:
            hint_text: "Password"
            id: password
            on_text: root.check_form()

        Input1:
            hint_text: "Confirm Password"
            id: confirm_password
            on_text: root.check_form()

        Label:
            text: root.error_message
            color: 1, 0, 0, 1
            font_size: "14sp"
            size_hint_y: None
            height: "20dp"
            halign: "left"
            text_size: self.width, None

        Widget:
            size_hint_y: 0.025

        Button1:
            text: "Register"
            on_press: root.register_button()
            disabled: not root.form_valid

        Button:
            text: "Back to Login"
            color: 0,0,0,1
            size_hint_y: None
            height: "30dp"
            background_color: 0,0,0,0
            on_press: root.go_to("login")

        Widget:
            size_hint_y: 0.4