<SelectRegister>:
    canvas.before:
        Color:
            rgba: 1,1,1,1
        Rectangle:
            pos: self.pos
            size: self.size
    BoxLayout:
        orientation: "vertical"
        padding: "50dp"
        spacing: "20dp"

        Widget:

        Button1:
            text: "Register Customer"
            on_press: root.go_register("customer")

        Button1:
            text: "Register Rider"
            on_press: root.go_register("rider")

        Widget: